name: Meow Package Testing action

on:
    push:
        branches:
            - Dev


jobs:
    pre-setup:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]
        steps:
            - run: echo "Setup project.."
            - name: Cloning repository
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{matrix.python-version}}
            - name: Install Hatch
              run: pip install hatch
    
    
    test:
        needs: pre-setup
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]
        steps:
            - run: echo "Setup project.."
            - name: Cloning repository
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{matrix.python-version}}
            
            - name: Install Hatch
              run: pip install hatch

            - name: Install twin
              run: pip install twine

            - name: Run tests
              run: hatch run test:pytest
            
            - name: Build package
              run: hatch build
            
            - name: Test package
              run: twine check dist/*
